import fs from "node:fs";
import path from "node:path";
import { archiveRun, type ArchiveResult } from "./archive.js";
import { commitRun, pushRun, type CommitResult, type PushResult } from "./gitflow.js";
import { reviewTask, verifyTask, type ReviewResult, type VerificationResult } from "./quality.js";
import { createDeliveryRun, type DeliveryRunResult } from "./run.js";
import { runCommand } from "./shell.js";
import { collectPatch, prepareWorktrees, type PatchCollectResult, type WorktreePrepareResult } from "./worktree.js";

export interface NewProjectDeliveryResult {
  runId: string;
  cwd: string;
  status: "archived" | "blocked";
  run: DeliveryRunResult;
  worktrees: WorktreePrepareResult;
  patches: PatchCollectResult[];
  verification: VerificationResult[];
  reviews: ReviewResult[];
  commit: CommitResult;
  push: PushResult;
  archive: ArchiveResult;
  projectWorktree: string;
}

function git(cwd: string, args: string[]): string {
  const result = runCommand("git", args, cwd);
  if (result.code !== 0) {
    throw new Error(result.stderr || result.error || `git ${args.join(" ")} failed`);
  }
  return result.stdout;
}

function optionalGit(cwd: string, args: string[]): boolean {
  return runCommand("git", args, cwd).code === 0;
}

export function ensureGitRepository(cwd: string): void {
  if (!optionalGit(cwd, ["rev-parse", "--is-inside-work-tree"])) {
    git(cwd, ["init"]);
  }
  if (!optionalGit(cwd, ["config", "user.email"])) {
    git(cwd, ["config", "user.email", "imfine@example.local"]);
  }
  if (!optionalGit(cwd, ["config", "user.name"])) {
    git(cwd, ["config", "user.name", "imfine"]);
  }
  if (!optionalGit(cwd, ["rev-parse", "--verify", "HEAD"])) {
    git(cwd, ["add", "."]);
    git(cwd, ["commit", "-m", "chore(imfine): initialize delivery run"]);
  }
}

function requirementText(run: DeliveryRunResult): string {
  return run.source.value.trim() || run.runId;
}

function writeProjectFoundation(worktree: string, run: DeliveryRunResult): void {
  const requirement = requirementText(run);
  fs.writeFileSync(path.join(worktree, ".gitignore"), ["node_modules/", "dist/", ".DS_Store", ""].join("\n"));
  fs.writeFileSync(path.join(worktree, "package.json"), `${JSON.stringify({
    name: "imfine-generated-project",
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      test: "node --test",
      lint: "node --check src/index.js && node --check test/index.test.js",
      format: "node -e \"console.log('format check: no formatter configured')\"",
      typecheck: "node --check src/index.js && node --check test/index.test.js",
      build: "node --check src/index.js"
    }
  }, null, 2)}\n`);
  fs.mkdirSync(path.join(worktree, "src"), { recursive: true });
  fs.mkdirSync(path.join(worktree, "test"), { recursive: true });
  fs.writeFileSync(path.join(worktree, "src", "index.js"), `export function createProjectSummary() {
  return {
    name: "imfine-generated-project",
    requirement: ${JSON.stringify(requirement)},
    status: "ready"
  };
}

export function createTask(title) {
  const normalized = String(title || "").trim();
  if (!normalized) throw new Error("Task title is required");
  return { title: normalized, done: false };
}

export function completeTask(task) {
  return { ...task, done: true };
}
`);
  fs.writeFileSync(path.join(worktree, "test", "index.test.js"), `import assert from "node:assert/strict";
import test from "node:test";
import { completeTask, createProjectSummary, createTask } from "../src/index.js";

test("project summary captures the requirement", () => {
  assert.equal(createProjectSummary().requirement, ${JSON.stringify(requirement)});
});

test("tasks can be created and completed", () => {
  const task = createTask("ship first feature");
  assert.deepEqual(completeTask(task), { title: "ship first feature", done: true });
});
`);
  fs.writeFileSync(path.join(worktree, "README.md"), `# imfine-generated-project

Generated by imfine from:

> ${requirement}

## Commands

- \`npm run test\`
- \`npm run lint\`
- \`npm run format\`
- \`npm run typecheck\`
- \`npm run build\`

## Structure

- \`src/index.js\`: initial project behavior.
- \`test/index.test.js\`: baseline tests.
- \`.imfine/\`: delivery run evidence and project knowledge.
`);
}

function writeProjectDocs(worktree: string, run: DeliveryRunResult): void {
  const requirement = requirementText(run);
  const docs = path.join(worktree, "docs");
  fs.mkdirSync(docs, { recursive: true });
  fs.writeFileSync(path.join(docs, "usage.md"), `# Usage

## Requirement

${requirement}

## Local Workflow

1. Install dependencies if future agents add any.
2. Run \`npm run test\`.
3. Run \`npm run lint\`, \`npm run typecheck\`, and \`npm run build\` before delivery.

## Delivery Evidence

This project was initialized by imfine as a first delivery run. Archive evidence is available under \`.imfine/runs/${run.runId}/archive\`.
`);
}

function taskWorktree(worktrees: WorktreePrepareResult, taskId: string): string {
  const task = worktrees.tasks.find((item) => item.task_id === taskId);
  if (!task) throw new Error(`Missing worktree for task ${taskId}`);
  return task.path;
}

function writeText(file: string, content: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function recordNewProjectDecisions(cwd: string, run: DeliveryRunResult): void {
  const runDir = run.runDir;
  writeText(path.join(runDir, "design", "architecture-decisions.md"), `# Architecture Decisions

## Decisions

- Project kind: new_project.
- Runtime: Node.js ES modules.
- Package manager: npm.
- Source layout: \`src/index.js\`.
- Test layout: \`test/index.test.js\`.
- Documentation layout: \`README.md\` and \`docs/usage.md\`.
- Git strategy: local \`imfine/${run.runId}\` run branch with task commits.

## Rationale

- The initial requirement can be satisfied with a dependency-free Node.js project.
- No database, cloud service, credential, or external production infrastructure is created.
- The generated scripts provide test, lint, format, typecheck, and build checks without installing external dependencies.
`);
  writeText(path.join(runDir, "design", "technical-solution.md"), `# Technical Solution

## Selected Stack

- Language/runtime: Node.js.
- Module system: ES modules.
- Tests: \`node:test\`.
- Static checks: \`node --check\`.
- Package manager: npm.

## Generated Structure

- \`package.json\`
- \`.gitignore\`
- \`README.md\`
- \`src/index.js\`
- \`test/index.test.js\`
- \`docs/usage.md\`

## Verification Commands

- \`npm run test\`
- \`npm run lint\`
- \`npm run format\`
- \`npm run typecheck\`
- \`npm run build\`
`);
  writeText(path.join(runDir, "analysis", "risk-analysis.md"), `# Risk Analysis

## Risks

- The first delivery uses a minimal local Node.js stack and does not provision external infrastructure.
- Missing remote is expected for new projects unless the user configures \`origin\`.
- Production security, authentication, persistence, deployment, and compliance remain future explicit work.

## High-Risk Areas Not Created

- Database.
- Cloud services.
- Paid services.
- Production credentials.
- Real external integrations.
`);
}

export function completeNewProjectDelivery(cwd: string, run: DeliveryRunResult): NewProjectDeliveryResult {
  void cwd;
  void run;
  throw new Error("New-project runtime delivery scaffolding has been removed. Prepare model execution packages and wait for Agent outputs instead.");
}

export function deliverNewProject(cwd: string, requirementArgs: string[]): NewProjectDeliveryResult {
  void cwd;
  void requirementArgs;
  throw new Error("New-project runtime delivery scaffolding has been removed. Use `run` to prepare Architect and Task Planner packages.");
}
